### ISSUE TITLE
dont load nar into memory and stream vec<u8>

### ISSUE THREAD

**Issue by Conni2461** [helsinki-systems/harmonia#1]
Use a filehandle and make a FileResponse

**Comment by ajs124** [comment]
as a datapoint, on slow hardware with slow storage (rpi4 + iscsi), an example download looks like this:
```
--2022-04-30 21:09:28--  http://127.0.0.1:5000/nar/0rgqgwkzkw225id109rmsp2lhgbax60dxcbna0azyskp6y6zf724.nar
Connecting to 127.0.0.1:5000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 558200352 (532M) [application/x-nix-archive]
Saving to: ‘/dev/null’

/dev/null                                                            100%[====================================================================================================================================================================>] 532.34M  89.6MB/s    in 5.9s    

2022-04-30 21:09:57 (89.8 MB/s) - ‘/dev/null’ saved [558200352/558200352]


real    0m28.581s
user    0m0.907s
sys     0m3.587s
```
so the actual download takes ~6s, but the whole process 29s. I'd assume most of that other time is _probably_ reading the nar into memory.

**Comment by Conni2461** [comment]
so `exportPath` in nix store will always have some part in memory. All we can do is write it into different sinks. The write to sink was chunked, with most chunks being 65536 bytes (from what i've seen).

I have a fix where we write these chunks into a NamedTempfile and then stream this file. But i would propose make a proposal that we only do that for nars greater a threshold otherwise still with a `vec<u8>`. Currently i have hardcoded 1024 * 32 * 32 but i would make this configurable so we can have different thresholds for different hosts. 

If that works i would add the configuration to the PR https://github.com/helsinki-systems/harmonia/pull/12

Does this PR improve performance? Also do you have a performance comparison with eris?

**Comment by ajs124** [comment]
with eris, it looks like this:
```
--2022-05-03 23:34:11--  http://127.0.0.1:5000/nar/a1m45s27j0q2wwjzzl1644hb1n3v460f.nar
Connecting to 127.0.0.1:5000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 558200352 (532M) [application/x-nix-archive]
Saving to: ‘/dev/null’

/dev/null                                                            100%[====================================================================================================================================================================>] 532.34M  17.9MB/s    in 28s     

2022-05-03 23:34:39 (19.3 MB/s) - ‘/dev/null’ saved [558200352/558200352]


real    0m28.116s
user    0m1.138s
sys     0m4.342s
```
so the download starts basically instantly.

#12 sadly does not seem to change the behavior described above. at least not significantly. I verified that it says `export with NamedTempFile` in the log.

**Comment by Conni2461** [comment]
Yeah okay. Thats sh** I cant make the ffi bindings for `exportPath` async right now, so they are blocking till that function is done. There is a `BufferedSink` in nix cpp code that may allow us to read a chunk, stream that, read another, but that might be a lot of work.
So have dropped that approach for now and just copy eris approach with running `nix-store --dump path` and streaming the stdout file handle. It greatly improves performance on my hardware and it instantly starts downloading.

For now `byte-ranges` are not implemented with that approach. If it also improves stuff on your low end hardware, ill add that back, squash my commits and then we can merge (hopefully). I am about to push my changes

**Comment by ajs124** [comment]
My low end hardware is also your low end hardware :P

Now the download starts instantly, yes. It doesn't show the total length though, which eris does.
iirc we evaluate that in varnish for caching, so we kind of need it.

I admittedly understand very little about this, but why can't you make the ffi bindings async? That seems like the best solution, no?

**Comment by Conni2461** [comment]
> My low end hardware is also your low end hardware :P

I know :laughing: 

> why can't you make the ffi bindings async

Mostly it comes down to the fact that i have no idea how to do that and very little documentation for ffi bindings in the first place. I found this crate: https://github.com/oxalica/async-ffi but i have no idea if that even solves our issue. Will give it a try. `nix-store --dump path` seemed like the solution that was double in a couple of hours rather than couple of days.

Re-added content-length and accept ranges in my last commit.

**Comment by ajs124** [comment]
Alright, then lets just go with the command and idk, maybe something magical will happen in the future. You never know…

**Comment by Conni2461** [comment]
I pushed the other approach here so we dont lose it: https://github.com/helsinki-systems/harmonia/tree/export_path_with_lib

I close this because we no longer load it into memory. I might revisit the other approach at some other time
