### ISSUE TITLE
Harmonia unable to process private key with trailing whitespace

### ISSUE THREAD

**Issue by mikepurvis** [helsinki-systems/harmonia#67]
Works fine without the config option set, but with it, I get:

```
$ /nix/store/n4knp1ma8kr8n7w7bvz86kydb6prcysd-harmonia/bin/harmonia
thread 'main' panicked at 'Unexpected error while extracting the secret key: InvalidByte(88, 10)', harmonia/src/main.rs:460:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Settings are very simple:

```
$ cat settings.toml
bind = "0.0.0.0:5001"
max_connection_rate = 256
priority = 50
sign_key_path = "/var/cache-priv-key.pem"
workers = 4
```

The key file looks like this:

```
$ cat /var/cache-priv-key.pem
hydra.elided.ai:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx==
```

Any ideas what I'm doing wrong here? This is with the current master built from source (20114c21d1c902a8f5ad7be7744df241a784a06d).

----

Looks like the issue is that the pem had been edited by `vim`, which automatically inserts a linefeed (byte 10) at the end of text files. Removing this corrects the issue— might be worth making Harmonia strip whitespace characters before attempting to decode the key?

**Comment by Conni2461** [comment]
Thanks for debugging, someone provided a fix that seemed to work in CI runs. So bug should be fixed with current master
